In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors

## Creating a Tensor:

In [ ]:
# scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [ ]:
# find the dimension of the tensor
scalar.ndim

0

In [ ]:
# get the item from the tensor (converted to int)
scalar.item()

8

In [ ]:
# 1D Tensor (Vector)
vec = torch.tensor([1, 2, 3])
print(vec)

# 2D Tensor (Matrix)
m = torch.tensor([[1, 2], [3, 4]])
print(m)

# 3D Tensor (Tensor)
t = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(t)

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## `.ndim` & `.shape` Property:

### 1. `.ndim` Property:

It just tells **how many dimentions (axes)** a tensor has.

### 2. `.shape` Property:

It tells the **exact size** of each dimension.

In [ ]:
print(vec.ndim) # couting no. of pairs of square brackets
print(m.ndim)
print(t.ndim)

1
2
3


In [ ]:
print(vec.shape)
print(m.shape)
print(t.shape)

torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 2, 2])


In [ ]:
# get the elements by index
print(m[0])
print(m[1])
print(m[0][1])
print("\n")

print("Tensor 't': ")
print("\n")
print(t[0])
print(t[1][1])

tensor([1, 2])
tensor([3, 4])
tensor(2)


Tensor 't': 


tensor([[1, 2],
        [3, 4]])
tensor([7, 8])


## Random Tensors

### Why Random Tensors?

Random tensors are important because the way many many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3407, 0.8970, 0.7021, 0.4732],
        [0.8001, 0.9664, 0.3503, 0.4896],
        [0.2562, 0.6229, 0.5708, 0.0177]])

## Zeros and Ones Tensors



In [ ]:
# create a tensor of all 0's
zero_tensor = torch.zeros(3, 4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all 1's
one_tensor = torch.ones(3, 4)
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# print the data type of the tensors
print(zero_tensor.dtype)
print(one_tensor.dtype)

torch.float32
torch.float32


## Creating Tensors In a Range and Tensors-like

### For range:

- use `torch.range()`

**WARNING**: `torch.range()` sooner to be depricated in newer PyTorch versions


Instead, use `pytorch.arange()`

In [ ]:
torch.arange(4, 16)

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
torch.arange(start=4, end=100, step=3)

tensor([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55,
        58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [ ]:
# creating tensors-like
random_zeros = torch.zeros_like(input=random_tensor)
random_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Tensors Datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 3.0],
                               dtype=None,
                               device=None, # what device is your tensor on
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 3.])

### What is `requires_grad` in PyTorch?

PyTorch **tracks gradient** when `requires_drad=True`. If it's `False` then it doesn't care about gradient.

### What is a Gradient?

In PyTorch, a **gradient** is quantity to define **how much something changes** when another thing changes.

### Why Do We Need Gradient?

In **Machine Learning**, the **gradient tells us how to adjust our model to get better result** (find the lowest loss). This is called **Gradient Descent**. Neural Networks use gradients to learn & improve.

When `required_grad=False` -> Just normal math, no gradients.

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 3.], dtype=torch.float16)

## Getting Information From Tensor (Tensor Attributes)

In [ ]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0337, 0.9868, 0.1252, 0.3328],
        [0.2496, 0.9197, 0.9229, 0.8658],
        [0.6067, 0.5515, 0.5658, 0.2339]])

In [ ]:
# find out details about tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (Tensor Operations)

Operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor1 + 10

tensor([11, 12, 13])

In [ ]:
# Multiple tensor by 10
tensor1 * 10

tensor([10, 20, 30])

In [ ]:
# Some in-built PyTorch functions
torch.mul(tensor1, 10)

tensor([10, 20, 30])

## Matrix Multiplication

Two main ways of performing of multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [ ]:
torch.matmul(tensor1, tensor1) # 1*1 + 2*2 + 3*3 = 14

tensor(14)

The resulting matrix has the shape of **outer dimention** of the multiplying matrices

For example;

- `(4, 5) @ (5, 7)` -> `(4, 7)`
- `(5, 6) @ (6, 3)` -> `(5, 3)`

In [ ]:
torch.matmul(torch.rand(4, 5), torch.rand(5, 3)).shape

torch.Size([4, 3])

### Taking Transpose Of a Matrix

In [ ]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
# taking tranpose
tensor_A.T
print(f"Shape of tensor_A: {tensor_A.shape}")
print(f"Shape of tensor_A.T: {tensor_A.T.shape}")

Shape of tensor_A: torch.Size([3, 2])
Shape of tensor_A.T: torch.Size([2, 3])


## Finding the min, max, mean sum (Tensor Aggregation)

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# finding the min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
# fidning the max
x.max(), torch.max(x)

(tensor(90), tensor(90))

### Finding the mean

To find the mean of a tensor, `tensor.mean()` method is used.
But the issue is, it doesn't work with the tensors with `dtype` = `long` or `64 bits`, because it requires floating point precision.

For this to work, we need to convert this to float-point representation.


In [ ]:
# converting to floating point
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
# finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# finding the index of min element in the tensor
x.argmin()

tensor(0)

In [ ]:
# finding the index of max element in the tensor
x.argmax()

tensor(9)

## Reshaping, Stacking, Squeezing and unsqueezing the Tensors


* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all `1` dimensions from the tensor
* Unsqueeze - Add a `1` dimension to a taget tensor
* Permute - Return a view of the input with the dimension permuted (swapped) in a certain way

In [ ]:
x = torch.arange(0., 10.)
x, x.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([10]))

In [ ]:
# adding an extra dimension
x_shaped = x.reshape(2, 5)
x_shaped, x_shaped.shape

# x_shaped = x.reshape(2, 3) --> this will throw error as 10 elements can't be fitted inside 2x3 tensor (6 elements)

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]),
 torch.Size([2, 5]))

In [ ]:
# change the view
z = x.view(2, 5)
z, z.shape

# changing x -> changes z as they share the same memory

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]),
 torch.Size([2, 5]))

In [ ]:
z[0][0] = 1
x, z

(tensor([1., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]))

In [ ]:
# stack tensors on top of each other

x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[1., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 10]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked


# note: vstack --> dim = 0 and hstack --> dim = 1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# permuate method: rearrages the dimension of a target tensor in a specified order

x_original = torch.rand(224, 220, 3) # [height, width, color channel]

# permuate the original tensor to rearrage the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 220, 3])
New shape: torch.Size([3, 224, 220])


# TENSOR = DATA + SHAPE + STRIDE

A **tensor** in PyTorch isn't just a blob of values. It's a combination of:

- `data`: a **contiguous** chunk of memory (1D list of raw values underneath)
- `shape`: the dimensions, like `[2, 3, 4]`
- `stride`: how many memory steps to jump to reach the next element in each dim

> **So technically:**
```python
Tensor = (data_pointer, shape, stride)
```

In [ ]:
x_original[0,0,0] = 2002
x_permuted[0,0,0] # changing x_original element -> changes x_permuted element

tensor(2002.)

## Indexing In Tensors

In [ ]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# indexing the above tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
print(x[0, 1], x[0, 1, 2])
print(x[:, :, 1])

tensor([4, 5, 6]) tensor(6)
tensor([[2, 5, 8]])


## PyTorch Tensors & NumPy

NumPy is a popular scientific Python computing library.
And because of this, PyTorch has the functionlity to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# numpy array to tensors
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

# dtype of tensor is float64 because the default dtype of numpy is float64 and both array and tensor are sharing the same memory

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# doing following changes the pointer of 'array'
print(f"Old pointer: {id(array)}")
array = array + 1
print(f"New Pointer: {id(array)}")

# before changing the pointer of 'array'
# if you write array[0] = 45 then,
# value of tensor changes too

Old pointer: 140257695549072
New Pointer: 140257695549168


In [ ]:
# tensor to numpy array
tensor = torch.arange(1, 10)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# reflexs the original dtype
numpy_tensor.dtype, tensor.dtype

(dtype('int64'), torch.int64)

In [ ]:
# same thing happens while converting tensor to numpy_tensor
tensor = tensor + 1
numpy_tensor

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reproducibility (Trying to take random out of ramdom)

In short, how neural networks learns:

`start with random numbers -> tensor operations -> update random numbers to try and make better representation of the data -> again -> again -> again...`

To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**.

Essentially, what random seed does is 'flavour' the randomness.

In [ ]:
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

tensor([[0.4179, 0.0812, 0.7185, 0.1537],
        [0.8407, 0.6637, 0.8493, 0.9585],
        [0.3866, 0.4588, 0.3455, 0.1821]])
tensor([[0.2231, 0.4605, 0.6398, 0.6571],
        [0.1373, 0.5587, 0.9480, 0.2746],
        [0.4081, 0.1300, 0.4921, 0.9787]])


In [ ]:
# let's make some random but reproducible tensor
RANDOM_SEED = 30
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Putting Tensors (and models) on GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computation.

In [ ]:
# create a tensor (default on CPU)

tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU (if available)

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_to_cuda = tensor.to(device)
tensor_to_cuda

tensor([1, 2, 3], device='cuda:0')

## Moving Tensors Back To GPU

If tensors on GPU, can't transform it to NumPy

In [ ]:
converted_numpy_tensor = tensor.cpu().numpy()
converted_numpy_tensor

array([1, 2, 3])