In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors

## Creating a Tensor:

In [8]:
# scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [9]:
# find the dimension of the tensor
scalar.ndim

0

In [10]:
# get the item from the tensor (converted to int)
scalar.item()

8

In [23]:
# 1D Tensor (Vector)
vec = torch.tensor([1, 2, 3])
print(vec)

# 2D Tensor (Matrix)
m = torch.tensor([[1, 2], [3, 4]])
print(m)

# 3D Tensor (Tensor)
t = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(t)

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## `.ndim` & `.shape` Property:

### 1. `.ndim` Property:

It just tells **how many dimentions (axes)** a tensor has.

### 2. `.shape` Property:

It tells the **exact size** of each dimension.

In [24]:
print(vec.ndim) # couting no. of pairs of square brackets
print(m.ndim)
print(t.ndim)

1
2
3


In [25]:
print(vec.shape)
print(m.shape)
print(t.shape)

torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 2, 2])
